// Application-wide constants

export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

export const GENDER_OPTIONS = ['Male', 'Female'];

export const INSTITUTIONS = [
  'University of Chittagong',
  'Chittagong University of Engineering and Technology',
  'Chittagong Medical College',
  'Chittagong Veterinary and Animal Sciences University',
  'Premier University',
  'International Islamic University Chittagong',
  'BGC Trust University Bangladesh',
  'East Delta University',
  'Port City International University',
  'Other',
];

export const DEPARTMENTS_CU = [
  'Accounting',
  'Anthropology',
  'Applied Chemistry and Chemical Engineering',
  'Arabic',
  'Bangla',
  'Bangladesh Studies',
  'Banking and Insurance',
  'Biochemistry & Molecular Biology',
  'Botany',
  'Chemistry',
  'Communication and Journalism',
  'Computer Science & Engineering',
  'Criminology and Police Science',
  'Development Studies',
  'Dramatics',
  'Economics',
  'Electrical & Electronic Engineering',
  'English',
  'Finance',
  'Fisheries',
  'Forestry and Environmental Sciences',
  'Genetic Engineering & Biotechnology',
  'Geography and Environmental Studies',
  'History',
  'Human Resource Management',
  'Institute of Education and Research',
  'Institute of Fine Arts',
  'Institute of Marine Sciences',
  'Institute of Modern Languages',
  'International Relations',
  'Islamic History and Culture',
  'Islamic Studies',
  'JNIRCMPS',
  'Law',
  'Management',
  'Marketing',
  'Mathematics',
  'Microbiology',
  'Music',
  'Oceanography',
  'Pali',
  'Persian Language & Literature',
  'Pharmacy',
  'Philosophy',
  'Physical Education & Sports Science',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Administration',
  'Sanskrit',
  'Sociology',
  'Soil Science',
  'Statistics',
  'Zoology',
];

// Department short form mapping (for database storage)
export const DEPARTMENT_SHORT_FORMS = {
  'Accounting': 'acc',
  'Anthropology': 'anthro',
  'Applied Chemistry and Chemical Engineering': 'acce',
  'Arabic': 'arabic',
  'Bangla': 'bangla',
  'Bangladesh Studies': 'bds',
  'Banking and Insurance': 'banking',
  'Biochemistry & Molecular Biology': 'bmb',
  'Botany': 'botany',
  'Chemistry': 'chem',
  'Communication and Journalism': 'comj',
  'Computer Science & Engineering': 'cse',
  'Criminology and Police Science': 'cps',
  'Development Studies': 'ds',
  'Dramatics': 'drama',
  'Economics': 'eco',
  'Electrical & Electronic Engineering': 'eee',
  'English': 'eng',
  'Finance': 'finance',
  'Fisheries': 'fisheries',
  'Forestry and Environmental Sciences': 'fes',
  'Genetic Engineering & Biotechnology': 'geb',
  'Geography and Environmental Studies': 'geo',
  'History': 'history',
  'Human Resource Management': 'hrm',
  'Institute of Education and Research': 'ier',
  'Institute of Fine Arts': 'finearts',
  'Institute of Marine Sciences': 'ims',
  'Institute of Modern Languages': 'iml',
  'International Relations': 'ir',
  'Islamic History and Culture': 'ihc',
  'Islamic Studies': 'isl',
  'JNIRCMPS': 'jnircmps',
  'Law': 'law',
  'Management': 'management',
  'Marketing': 'marketing',
  'Mathematics': 'math',
  'Microbiology': 'micro',
  'Music': 'music',
  'Oceanography': 'ocean',
  'Pali': 'pali',
  'Persian Language & Literature': 'persian',
  'Pharmacy': 'pharmacy',
  'Philosophy': 'philosophy',
  'Physical Education & Sports Science': 'pes',
  'Physics': 'phy',
  'Political Science': 'politicalscience',
  'Psychology': 'psy',
  'Public Administration': 'publicad',
  'Sanskrit': 'sanskrit',
  'Sociology': 'sociology',
  'Soil Science': 'soil',
  'Statistics': 'stat',
  'Zoology': 'zoo',
};

// Reverse mapping: short form to full form
export const SHORT_FORM_TO_DEPARTMENT = Object.fromEntries(
  Object.entries(DEPARTMENT_SHORT_FORMS).map(([full, short]) => [short, full])
);

export const ROUTES = {
  HOME: '/',
  FIND_DONOR: '/find-donor',
  DONOR_REGISTRATION: '/donor-registration',
  VOLUNTEER_REGISTRATION: '/volunteer-registration',
  AVAILABILITY_REQUEST: '/availability-request',
  ABOUT: '/about',
  FAQ: '/faq',
  TESTIMONIALS: '/testimonials',
  GALLERY: '/gallery',
  EVENTS: '/events',
  SUCCESS_STORIES: '/success-stories',
  BLOGS: '/blogs',
  CONTACT: '/contact',
  ARCHITECTURE: '/architecture',
};

export const ELIGIBILITY_CRITERIA = {
  minAge: 18,
  maxAge: 65,
  minWeight: 50,
  minHemoglobin: 12.5,
  donationInterval: 56, // days
};

export const SOCIAL_LINKS = {
  facebook: '#',
  twitter: '#',
  instagram: '#',
  linkedin: '#',
};
